package AEDProject;
// Generated 24-ene-2017 12:02:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private short codC;
	private String nombreC;
	private String descripcion;
	private Set productos = new HashSet(0);

	public Categoria() {
	}

	public Categoria(short codC) {
		this.codC = codC;
	}

	public Categoria(short codC, String nombreC, String descripcion, Set productos) {
		this.codC = codC;
		this.nombreC = nombreC;
		this.descripcion = descripcion;
		this.productos = productos;
	}

	public short getCodC() {
		return this.codC;
	}

	public void setCodC(short codC) {
		this.codC = codC;
	}

	public String getNombreC() {
		return this.nombreC;
	}

	public void setNombreC(String nombreC) {
		this.nombreC = nombreC;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
