package AEDProject;
// Generated 24-ene-2017 12:02:12 by Hibernate Tools 3.4.0.CR1

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private short codP;
	private Categoria categoria;
	private String nombreP;
	private Short tamano;
	private String dos;

	public Producto() {
	}

	public Producto(short codP, Categoria categoria) {
		this.codP = codP;
		this.categoria = categoria;
	}

	public Producto(short codP, Categoria categoria, String nombreP, Short tamano, String dos) {
		this.codP = codP;
		this.categoria = categoria;
		this.nombreP = nombreP;
		this.tamano = tamano;
		this.dos = dos;
	}

	public short getCodP() {
		return this.codP;
	}

	public void setCodP(short codP) {
		this.codP = codP;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getNombreP() {
		return this.nombreP;
	}

	public void setNombreP(String nombreP) {
		this.nombreP = nombreP;
	}

	public Short getTamano() {
		return this.tamano;
	}

	public void setTamano(Short tamano) {
		this.tamano = tamano;
	}

	public String getDos() {
		return this.dos;
	}

	public void setDos(String dos) {
		this.dos = dos;
	}

}
